/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.deployment.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.fraunhofer.ipa.deployment.DeploymentRuntimeModule;
import de.fraunhofer.ipa.deployment.DeploymentStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DeploymentIdeSetup extends DeploymentStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DeploymentRuntimeModule(), new DeploymentIdeModule()));
	}
	
}
