/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.deployment.ide;


/**
 * Use this class to register ide components.
 */
public class DeploymentIdeModule extends AbstractDeploymentIdeModule {
}
