/*
 * generated by Xtext 2.26.0
 */
package de.ipa.fraunhofer.deployment.tests

import com.google.inject.Inject
import de.ipa.fraunhofer.deployment.yaml.Yaml
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(YamlInjectorProvider)
class YamlParsingTest {
	@Inject
	ParseHelper<Yaml> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
