/*
 * generated by Xtext 2.26.0
 */
package de.ipa.fraunhofer.deployment.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class YamlWebModule extends AbstractYamlWebModule {
}
