/*
 * generated by Xtext 2.26.0
 */
package de.ipa.fraunhofer.deployment.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class YamlUiModule extends AbstractYamlUiModule {

	public YamlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
