/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.deployment;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DeploymentStandaloneSetup extends DeploymentStandaloneSetupGenerated {

	public static void doSetup() {
		new DeploymentStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
