/*
 * generated by Xtext 2.26.0
 */
package de.ipa.fraunhofer.deployment;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class YamlStandaloneSetup extends YamlStandaloneSetupGenerated {

	public static void doSetup() {
		new YamlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
